### PR TITLE
feat/refactor: ui/ux

### PR DESCRIPTION
**Pull request by wridgeu**
Hi Marian,

as suggested on twitter I tried coming up with something "more aligned" (I'm still not a UX genius haha). :D I went with a form view as everything in there reminded me of kind of a form for data input and a "submit" at the end to get a result. 

I also added some typings, switched the file download with a UI5 native API, added a QoL change so I can use the Enter button on the first two inputs and added a favicon as well as adjusted the page title.

## Side by Side (Before & After)

Ignore the little test data I had entered on the left side. ^^

image

Let me know what you think.

## Further Suggestion

You could think about adding [Open Graph](https://ogp.me/) meta tags so you have a nice preview when sharing the page on social media. 

BR
Marco

### CODE REVIEW

**Comment by marianfoo** [comment]
Wow, lot of work from you.
Can't test it right now, how does it look on mobile?

**Comment by wridgeu** [comment]
>Can't test it right now, how does it look on mobile?
Ah damn! I forgot to check mobile towards the end. Because the form itself needed to have a fixed width (due to some responsiveness calcs messing with the focus handler & sizing) it doesn't look too nice now. I'll see if I can do something there. ^^

**Comment by marianfoo** [comment]
I've done the same mistake:D
That's why I failed 😄

**Comment by wridgeu** [comment]
😄😅 ... I understand haha 

I added a simple fix for that now. The form has a max-width so that it is allowed to shrink for mobile and expand for desktop to it's max. Without it, the form would keep expanding upon entering more tokens. Thats "ok" but doesn't look nice when using it. 

## Mobile View (Pixel 5)

with scrollbar, screenshot taken with little scroll down

image

## Without width restriction

By adding more and more tokens the design would be responsive, yes, but ugly :D so you'd either have to restrict the multi inputs themselves or any parent or adjust the grid itself a bit more, depends. 

image

But the max-width should be fine, I guess. ^^

**Comment by marianfoo** [comment]
Cheers, let's merge and test it on production 😅

**Comment by marianfoo** [comment]
Looks definitely better and worked.
Cheers!

**Comment by wridgeu** [comment]
🍻

**Pull request merged**
